import '../../../node_modules/jquery/dist/jquery'
import '../../components/logo/logo.svg'
import '../../images/backgrounds/sign.jpg'
import '../../favicons/favicons'
import '../../components/header-menu/header-menu'
import './sign-in.scss'